### ISSUE TITLE
Support notifications for other events

### ISSUE THREAD

**Issue by anoved** [anoved/OctoPrint-EmailNotifier#1]
Currently notifications are only sent in response to the `PrintDone` event, but there are [many others](http://docs.octoprint.org/en/master/events/index.html).

**Comment by anoved** [comment]
@foosel @dcwalmsley I created a `multievent` branch of this plugin that supports email notifications for arbitrary events as discussed in foosel/Octoprint#1070. It is configured with a dict of [event names](http://docs.octoprint.org/en/master/events/index.html#available-events), each with their own notification settings. Any of the event's payload properties can be used in the message template.

Here's an example of what the config looks like now:

```yaml
  emailnotifier:
    _config_version: 2
    mail_server: smtp.gmail.com
    mail_username: jim.devona@gmail.com
    notifications:
      FileSelected:
        body: '{file} selected for printing.'
        enabled: true
        snapshot: false
        title: Selected {filename}
      MovieDone:
        body: Timelapse of printing {gcode} saved as {movie}.
        enabled: true
        snapshot: false
        title: 'Timelapse rendered: {movie_basename}'
      PrintDone:
        body: '{file} done in {time}.'
        enabled: true
        snapshot: true
        title: 'Print complete: {file}'
    recipient_address: jim@anoved.net
```

Unfortunately I haven't figured out how to make a settings template interface for `notifications`, so it has to be edited manually.
